dist: trusty
language: java
jdk:
  - oraclejdk8
  - openjdk11

script:
  - travis_retry ./gradlew check jacocoTestReport
  - travis_retry bash <(curl -s https://codecov.io/bash)
  - travis_retry ./gradlew integrationTest
